export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//SITE
export const SITES_LOADING = "SITES_LOADING";
export const SITES_LOADED = "SITES_LOADED";
export const SITES_LOADING_FAIL = "SITES_LOADING_FAIL";
export const SET_SELECTED_SITE = "SET_SELECTED_SITE";
export const STATISTICS_LOADED = "STATISTICS_LOADED";
export const SET_DATES = "SET_DATES";
